### ISSUE TITLE
Magics didnt works

### ISSUE THREAD

**Issue by Observeur** [myQLM/myqlm-issues#6]
Hello,
I am trying to use the myqlm on my device, but the magics tool for showing the automats don"t work.
The command %quatdisplay say "command not found

**To Reproduce**

**Expected behavior**
help me to make it working ^^'

**Screenshots**
it's not à screen, it's a copy/paste of error message went i use "python -m qat.magics.install" :
Traceback (most recent call last):
  File "C:\Users\coutur03\AppData\Local\Programs\Python\Python38\lib\site-packages\wand\api.py", line 151, in <module>
    libraries = load_library()
  File "C:\Users\coutur03\AppData\Local\Programs\Python\Python38\lib\site-packages\wand\api.py", line 140, in load_library
    raise IOError('cannot find library; tried paths: ' + repr(tried_paths))
OSError: cannot find library; tried paths: []

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\coutur03\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\coutur03\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\coutur03\AppData\Local\Programs\Python\Python38\lib\site-packages\qat\magics\install.py", line 20, in <module>
    from qat.core.magic.install import install_qlm_magics
  File "__init__.py", line 22, in init qat.core.magic.__init__
  File "C:\Users\coutur03\AppData\Local\Programs\Python\Python38\lib\site-packages\qat\core\magic\magic.py", line 29, in <module>
    from wand.image import Image as WImage
  File "C:\Users\coutur03\AppData\Local\Programs\Python\Python38\lib\site-packages\wand\image.py", line 18, in <module>
    from . import assertions
  File "C:\Users\coutur03\AppData\Local\Programs\Python\Python38\lib\site-packages\wand\assertions.py", line 155, in <module>
    from .color import Color  # noqa: E402
  File "C:\Users\coutur03\AppData\Local\Programs\Python\Python38\lib\site-packages\wand\color.py", line 10, in <module>
    from .api import library
  File "C:\Users\coutur03\AppData\Local\Programs\Python\Python38\lib\site-packages\wand\api.py", line 175, in <module>
    raise ImportError('MagickWand shared library not found.\n'
ImportError: MagickWand shared library not found.
You probably had not installed ImageMagick library.
Try to install:
  https://docs.wand-py.org/en/latest/guide/install.html#install-imagemagick-on-windows

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser edge
 - Version 88.0.705.56

**Additional context**
I have just install the myQLM and try to use it with the didactitiel on jupyter notebook

**Comment by amitsaha2806** [comment]
Try '%jsqatdisplay' instead of '%qatdisplay'.

**Comment by Observeur** [comment]
![error](https://user-images.githubusercontent.com/78352322/106752433-bbc76a80-662a-11eb-9355-ef5733ef75cb.jpg)

Hum, no, %jsqatdisplay don't work ...

I also have an error after when using !cat or !aquasm2circ :
![ErrorCat](https://user-images.githubusercontent.com/78352322/106752794-24aee280-662b-11eb-8f89-13f4a5869840.jpg)

Have I miss something in the install ?
(I have follow this :
https://myqlm.github.io/myqlm_specific/install.html )

**Comment by amitsaha2806** [comment]
Can you please again reinstall myQLM magics:

python -m qat.magics.install

**Comment by ArnaudGazda** [comment]
Hi Observeur,

Our `qatdisplay` magic requires `wand` module to display quantum circuits inside Jupyter notebooks (cf. [Prerequisites](https://myqlm.github.io/myqlm_specific/install.html#prerequisites) in the documentation)

The `wand` module requires extra tools to work (like the *ImageMagick* library). Since you are using Windows, please go to the [Install ImageMagick on Windows](https://docs.wand-py.org/en/latest/guide/install.html#install-imagemagick-on-windows) page to download this library.
Once you have installed this library, you can install myQLM magics again:

```
python -m qat.magics.install
```

I hope it will fix your issue.

Best,

Arnaud

**Comment by Observeur** [comment]
That's it !!
it work after installing imageMagik library !

Thank you !
