### ISSUE TITLE
'LineQubit' object has no attribute 'validate_args'

### ISSUE THREAD

**Issue by pmirallesr** [myQLM/myqlm-issues#9]
**Describe the bug**
I created a circuit and tried to print it to the terminal through translating it to cirq 

**To Reproduce**
Run 
```
# Create quantum circuit
# Create a Program
qprog = Program()
# Number of qbits
nbqbits = 5
# Allocate some qbits
qbits = qprog.qalloc(nbqbits)
# Encoder circuit:
datapoint = [[1, 0, 1, 0, 0]]
for i, xi in enumerate(datapoint):
    if xi:
        qprog.apply(gates.X, qbits[i])
circuit = qprog.to_circ()
google_circ = qlm_to_cirq(circuit)
print(google_circ)
```

**Expected behavior**
A print of the circuit

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Firefox
 - Version 86

**Additional context**
Traceback: 
```
/home/pmirallesr/.vscode/extensions/ms-python.python-2021.2.625869727/pythonFiles/lib/python/debugpy/launcher 37783 -- /home/pmirallesr/Documents/IRT/QuantumML/myQLM/Supervised.py 
Traceback (most recent call last):
  File "/home/pmirallesr/Documents/IRT/QuantumML/myQLM/Supervised.py", line 95, in <module>
    google_circ = qlm_to_cirq(circuit)
  File "/home/pmirallesr/.local/lib/python3.8/site-packages/qat/interop/cirq/converters.py", line 678, in qlm_to_cirq
    cirq_circ.append(gate.on(*[qreg[i] for i in op.qbits]))
  File "/home/pmirallesr/miniconda3/envs/quantumAI/lib/python3.8/site-packages/cirq/ops/raw_types.py", line 201, in on
    return gate_operation.GateOperation(self, list(qubits))
  File "/home/pmirallesr/miniconda3/envs/quantumAI/lib/python3.8/site-packages/cirq/ops/gate_operation.py", line 40, in __init__
    gate.validate_args(qubits)
AttributeError: 'LineQubit' object has no attribute 'validate_args'
```

**Comment by jcjaskula** [comment]
There is a commit and a pending pull request that will solve this bug. It should not take long.
